### ISSUE TITLE
Integrating with servant-client

### ISSUE THREAD

**Issue by jkarni** [ElvishJerricco/servant-haxl-client#1]
Someone just pointed this out to me, and it looks wonderful. I was wondering what the main difficulties in having it not be a fork are (i.e., still have it as a separate package, but one that provides only the `DataSource` etc. instances for `Req`). I'd imagine we'd need another argument to `client`, but aside from that any serious blockers? And would you be interested in going this route?

**Comment by ElvishJerricco** [comment]
I'm sorry, I'm not exactly sure what you're suggesting?

**Comment by jkarni** [comment]
Having this not be a fork of servant-client, but instead a library on top of it.

**Comment by ElvishJerricco** [comment]
Ah I see. Well the purpose of this package was initially to provide GHCJS compatible servant clients, and Haxl was sort of just something I threw in. Honestly I'm not happy with the results of this package. It hides behind preprocessor crap to differentiate between GHC and GHCJS. What I would like to see is some mechanism that enables `servant-client` to be abstract over the network implementation. Then the user gets to pass in some parameter that provides the tools for actually performing the requests. With a more abstract interface like that, it would be trivial to wrap the results in Haxl to get the parallelization / caching.

**Comment by jkarni** [comment]
Ok, I think I also got a sense for what is necessary. Closing this, and will continue in the `servant` repo when back from vacation.

Thanks a lot!
